name = "Burnout Pack"
author = "Yamayaki"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c0ec2a3292ccff620a52a127e144b158b4e77b3650c84090f0332d113850bd2"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
