name = "Burnout Pack"
author = "Yamayaki"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75503f3236b191b65593946abdddd47af8fca38833a13a2098588f713321475d"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
