name = "Burnout Pack"
author = "Yamayaki"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b8a83dece4676548cf0480ac43f66767bc741336eb570dd3954152e84b9adba"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
