name = "Burnout Pack"
author = "Yamayaki"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b26eb933fdf9c0a2c4e1f20d949558ebaf90abe08759d2d0b50e430f448b0f9"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
