name = "Burnout Pack"
author = "Yamayaki"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e0d3c8b7e2fff1867a783020ed2d4a402ae7e8efe3222bece12e8ef9876f9c5"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
