name = "Burnout Pack"
author = "Yamayaki"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "006fbc840eb1b7bf4d2391374802d32f5054c62aaba6ff22cda469cf8a0ff4dd"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
