name = "Burnout Pack"
author = "Yamayaki"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73fad9dcaee5a28ef49011f7d185a71b19f11c4577f9eaa5738b18cc85d4567d"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
