name = "Burnout Pack"
author = "Yamayaki"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7ff919f874044e7c3eda92b48d5a1dcff14241a4c917a7a9688f4bb8fd64580"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
