name = "Burnout Pack"
author = "Yamayaki"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7876ac28c1bc3b376d3a01a45559b292a77ca8940af4f461803f9fc735007946"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
